name: Task
description: Epic을 구성하는 단일 작업(Task) 이슈입니다.
title: "[TASK]"
labels: ["TASK"]
body:
  - type: input
    id: related-epic
    attributes:
      label: 관련 Epic
      description: 이 Task가 속한 Epic 이슈 번호를 작성해주세요
      placeholder: "#EPIC_ISSUE_NUMBER"
    validations:
      required: true

  - type: textarea
    id: task-goal
    attributes:
      label: 작업 목적
      description: 이 Task에서 달성해야 할 목표를 간단히 작성해주세요
      placeholder: |
        예시:
        - 유형별로 문제 목록을 조회할 수 있는 API를 구현한다.
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 구현 내용
      description: 구현해야 할 내용을 구체적으로 작성해주세요
      placeholder: |
        - `GET /problems?type=` API 엔드포인트 구현
        - 응답 데이터 형식 정의
        - 에러 케이스 처리
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 완료 조건 (Acceptance Criteria)
      description: 이 Task가 완료되었다고 판단할 수 있는 조건을 체크리스트로 작성해주세요
      placeholder: |
        - [ ] API 정상 응답 확인
        - [ ] 예외 케이스 처리 완료
        - [ ] 테스트 통과
      value: |
        - [ ]
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Blocked By
      description: 이 Task가 블로킹되는 이슈나 조건이 있다면 작성해주세요
      placeholder: |
        - #123 (API 스펙 정의 이슈)
        - 디자인 시안 필요
    validations:
      required: false
